// Generated by CoffeeScript 1.10.0
(function() {
  " Transpiled from 'src/app.coffee' to 'app.js'";
  var Eureca, app, bodyparser, eureca, express, game, path, server;

  path = require('path');

  express = require('express');

  app = exports.app = express();

  Eureca = require('eureca.io');

  eureca = new Eureca.Server;

  game = exports.game = require('./models/Game');

  app.use(express["static"](path.join(__dirname, 'public')));

  app.set('view engine', 'jade');

  app.use(require('express-session')({
    secret: '1234567890QWERTY',
    resave: true,
    saveUninitialized: true
  }));

  app.use(require('cookie-parser')());

  bodyparser = require('body-parser');

  app.use(bodyparser.json());

  app.use(bodyparser.urlencoded({
    extended: true
  }));

  app.use('/', require('./routes'));

  app.set('port', process.env.PORT || 5000);

  server = app.listen(app.get('port', function() {
    var host, port;
    host = server.address().address;
    port = app.get('port');
    return console.log("Application server running at http://" + host + ":" + port);
  }));

  eureca.attach(server);

  eureca.onConnect(function(conn) {
    console.log("New Client id: " + conn.id);
    return console.log("New Client remote address: " + conn.remoteAddress);
  });

  eureca.onDisconnect(function(conn) {
    return console.log("Client disconnected " + conn.id);
  });

}).call(this);
