// Generated by CoffeeScript 1.10.0
(function() {
  " Transpiled from 'src/app.coffee' to 'app.js'";
  var app, bodyparser, express, game, path, server;

  path = require('path');

  express = require('express');

  app = express();

  app.use(express["static"](path.join(__dirname, 'public')));

  app.set('view engine', 'jade');

  app.use(require('express-session')({
    secret: '1234567890QWERTY',
    resave: true,
    saveUninitialized: true
  }));

  app.use(require('cookie-parser')());

  bodyparser = require('body-parser');

  app.use(bodyparser.json());

  app.use(bodyparser.urlencoded({
    extended: true
  }));

  app.use('/', require('./controllers'));

  server = app.listen(5000, function() {
    var host, port;
    host = 'localhost';
    port = server.address().port;
    return console.log("Application server running at http://" + host + ":" + port);
  });

  game = require('./models/Game');

  exports.app = app;

  exports.game = game;

}).call(this);
