// Generated by CoffeeScript 1.10.0
(function() {
  var app, bodyparser, express, server;

  express = require('express');

  app = express();

  app.set('view engine', 'jade');

  app.use(express["static"]('public'));

  app.use(require('express-session')({
    secret: '1234567890QWERTY',
    resave: true,
    saveUninitialized: true
  }));

  bodyparser = require('body-parser');

  app.use(bodyparser.json());

  app.use(bodyparser.urlencoded({
    extended: true
  }));

  app.get('/', function(req, res) {
    return res.redirect('/start');
  });

  app.route('/start').get(function(req, res) {
    return res.render('start');
  }).post(function(req, res) {
    var target_username;
    target_username = req.body.username;
    if (target_username) {
      req.session.username = target_username;
      return res.redirect('play');
    } else {
      return res.render('start');
    }
  });

  app.route('/play').get(function(req, res) {
    return res.render('play');
  }).post(function(req, res) {
    res.contentType('json');
    return res.send({
      player_data: {
        username: req.session.username,
        x: 200,
        y: 250
      },
      game_data: {}
    });
  });

  server = app.listen(5000, function() {
    var host, port;
    host = 'localhost';
    port = server.address().port;
    return console.log("Application server running at http://" + host + ":" + port);
  });

  module["export"] = app;

}).call(this);
