// Generated by CoffeeScript 1.10.0
(function() {
  var app;

  app = require('app').app;

  app.use('view engine', 'jade');

  app.get('/', function(req, res) {
    return res.redirect('/start');
  });

  app.route('/start').get(function(req, res) {
    return console.log('get world');
  }).post(function(req, res) {
    return console.log('post world');
  });

  app.route('/play').get(function(req, res) {
    return res.render('play');
  });

}).call(this);
