// Generated by CoffeeScript 1.10.0
(function() {
  " Transpiled from 'src/models/Game.coffee' to 'models/Game.js'";
  var Game, Player;

  Player = require('./Player');

  Game = (function() {
    function Game() {
      this.players = {};
    }

    Game.prototype.addPlayer = function(fingerprint, remote, username, x, y) {
      if (x == null) {
        x = 0;
      }
      if (y == null) {
        y = 0;
      }
      return this.players[fingerprint] = new Player(this, fingerprint, remote, username, x, y);
    };

    Game.prototype.removePlayer = function(fingerprint) {
      return delete this.players[fingerprint];
    };

    Game.prototype.usernameExists = function(username) {
      var player;
      return username === (function() {
        var i, len, ref, results;
        ref = this.players;
        results = [];
        for (i = 0, len = ref.length; i < len; i++) {
          player = ref[i];
          results.push(player.username);
        }
        return results;
      }).call(this);
    };

    return Game;

  })();

  module.exports = new Game;

}).call(this);
