// Generated by CoffeeScript 1.10.0
(function() {
  " Transpiled from 'src/models/Game.coffee' to 'models/Game.js'";
  var Game, Player;

  Player = require('./Player');

  Game = (function() {
    function Game() {
      this.players = {};
    }

    Game.prototype.addPlayer = function(id, remote, x, y) {
      var player;
      if (x == null) {
        x = 50;
      }
      if (y == null) {
        y = 50;
      }
      player = new Player(this, id, remote, x, y);
      return this.players[id] = player;
    };

    Game.prototype.removePlayer = function(id) {
      return delete this.player[id];
    };

    return Game;

  })();

  module.exports = new Game;

}).call(this);
