// Generated by CoffeeScript 1.10.0
(function() {
  " Transpiled from 'src/models/Player.coffee' to 'models/Player.js'";
  var Player;

  Player = (function() {
    function Player(game, id, remote, x, y) {
      this.game = game;
      this.id = id;
      this.remote = remote;
      this.x = x != null ? x : 0;
      this.y = y != null ? y : 0;
    }

    return Player;

  })();

  module.exports = Player;

}).call(this);
