// Generated by CoffeeScript 1.10.0
(function() {
  " Transpiled from 'src/models/Player.coffee' to 'models/Player.js'";
  var Player;

  Player = (function() {
    function Player(game, username, x, y) {
      this.game = game;
      this.username = username;
      this.x = x != null ? x : 50;
      this.y = y != null ? y : 50;
    }

    return Player;

  })();

  module.exports = Player;

}).call(this);
