// Generated by CoffeeScript 1.10.0

/* Player.coffee */

(function() {
  var Player;

  Player = (function() {
    function Player(game, fingerprint, remote, username, x, y) {
      this.game = game;
      this.fingerprint = fingerprint;
      this.remote = remote;
      this.username = username;
      this.x = x;
      this.y = y;
    }

    return Player;

  })();

  module.exports = Player;

}).call(this);
